apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pharming-1
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pharming-1
        spec:
          containers:
          - name: pharming-1
            image: batteryho/pharming:v0.3
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 8100
          restartPolicy: Never